export const PERMISSIONS = [
  { id: "perm_view_pos", name: "view_pos", description: "Open the point of sale", category: "pos" },
  { id: "perm_create_order", name: "create_order", description: "Create new orders", category: "pos" },
  { id: "perm_modify_order", name: "modify_order", description: "Edit order items and status", category: "pos" },
  { id: "perm_apply_discount", name: "apply_discount", description: "Apply discounts to an order", category: "pos" },
  { id: "perm_void_order", name: "void_order", description: "Void an order or cancel items", category: "pos" },
  { id: "perm_refund_payment", name: "refund_payment", description: "Refund a payment", category: "pos" },
  { id: "perm_close_order", name: "close_order", description: "Close and complete an order", category: "pos" },
  { id: "perm_manage_payments", name: "manage_payments", description: "Record and manage payments", category: "pos" },
  { id: "perm_view_inventory", name: "view_inventory", description: "View stock levels", category: "inventory" },
  { id: "perm_adjust_inventory", name: "adjust_inventory", description: "Adjust stock and record waste", category: "inventory" },
  { id: "perm_approve_transfer", name: "approve_transfer", description: "Approve stock transfers", category: "inventory" },
  { id: "perm_manage_products", name: "manage_products", description: "Create and edit products", category: "catalog" },
  { id: "perm_manage_prices", name: "manage_prices", description: "Change prices and selling units", category: "catalog" },
  { id: "perm_manage_staff", name: "manage_staff", description: "Invite and manage staff", category: "people" },
  { id: "perm_manage_roles", name: "manage_roles", description: "Manage roles and permissions", category: "people" },
  { id: "perm_manage_customers", name: "manage_customers", description: "Manage guest and VIP records", category: "people" },
  { id: "perm_update_ticket", name: "update_ticket", description: "Accept, prepare and hand over station tickets", category: "pos" },
  { id: "perm_clock_shift", name: "clock_shift", description: "Clock in and out of shifts", category: "people" },
  { id: "perm_manage_events", name: "manage_events", description: "Manage events", category: "club" },
  { id: "perm_manage_reservations", name: "manage_reservations", description: "Manage reservations", category: "club" },
  { id: "perm_manage_vip", name: "manage_vip", description: "Manage VIP packages and guests", category: "club" },
  { id: "perm_manage_floor", name: "manage_floor", description: "Edit floors, sections and tables", category: "club" },
  { id: "perm_view_reports", name: "view_reports", description: "View reports and analytics", category: "reporting" },
  { id: "perm_view_audit_logs", name: "view_audit_logs", description: "View the audit log", category: "reporting" },
  { id: "perm_manage_branches", name: "manage_branches", description: "Create and manage branches", category: "admin" },
] as const;

export const ALL_PERMISSIONS = PERMISSIONS.map((p) => p.name);

export const ROLES = [
  { id: "role_owner", name: "Organization Owner", description: "Full organization access", sortOrder: 1 },
  { id: "role_admin", name: "Administrator", description: "System administration", sortOrder: 2 },
  { id: "role_gm", name: "General Manager", description: "Operational management across branches", sortOrder: 3 },
  { id: "role_branch_manager", name: "Branch Manager", description: "Manages an assigned branch", sortOrder: 4 },
  { id: "role_event_manager", name: "Event Manager", description: "Events and reservations", sortOrder: 5 },
  { id: "role_inventory_manager", name: "Inventory Manager", description: "Stock and inventory", sortOrder: 6 },
  { id: "role_cashier", name: "Cashier", description: "POS and payment operations", sortOrder: 7 },
  { id: "role_waiter", name: "Waiter", description: "Tables and orders", sortOrder: 8 },
  { id: "role_bartender", name: "Bartender", description: "Bar operations", sortOrder: 9 },
  { id: "role_kitchen", name: "Kitchen Staff", description: "Kitchen operations", sortOrder: 10 },
  { id: "role_floor", name: "Floor Staff", description: "Floor operations", sortOrder: 11 },
] as const;

const viewOnly = ["view_pos", "view_inventory"];

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  role_owner: [...ALL_PERMISSIONS],
  role_admin: [...ALL_PERMISSIONS],
  role_gm: [
    ...ALL_PERMISSIONS.filter((p) => p !== "manage_branches"),
  ],
  role_branch_manager: [
    "manage_customers",
    "view_pos",
    "update_ticket",
    "create_order",
    "modify_order",
    "apply_discount",
    "void_order",
    "refund_payment",
    "close_order",
    "manage_payments",
    "view_inventory",
    "adjust_inventory",
    "approve_transfer",
    "manage_products",
    "manage_prices",
    "manage_staff",
    "clock_shift",
    "manage_events",
    "manage_reservations",
    "manage_vip",
    "manage_floor",
    "view_reports",
    "view_audit_logs",
  ],
  role_event_manager: [
    "manage_customers",
    "view_pos",
    "view_inventory",
    "manage_events",
    "manage_reservations",
    "manage_vip",
    "view_reports",
  ],
  role_inventory_manager: [
    "view_pos",
    "view_inventory",
    "adjust_inventory",
    "approve_transfer",
    "manage_products",
    "view_reports",
  ],
  role_cashier: [
    "manage_customers",
    "view_pos",
    "create_order",
    "modify_order",
    "close_order",
    "manage_payments",
    "view_inventory",
  ],
  role_waiter: [
    "manage_customers",
    "view_pos",
    "create_order",
    "modify_order",
    "close_order",
    "manage_reservations",
  ],
  // The station confirms its own handover. The waiter who entered the order
  // must not be able to mark it served and free the table early.
  role_bartender: [...viewOnly, "update_ticket"],
  role_kitchen: [...viewOnly, "update_ticket"],
  role_floor: [
    "manage_customers",
    "view_pos",
    "create_order",
    "modify_order",
    "manage_reservations",
  ],
};
